apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: muhammadrivaldy05/dealljobs
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: backend-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: backend-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: backend-secret
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TELEGRAM_TOKEN
                  name: backend-secret
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  key: TELEGRAM_CHAT_ID
                  name: backend-secret
            - name: DB_ADDRESS_SECURITY
              value: mysql-security-service
            - name: DB_ADDRESS_USER
              value: mysql-user-service
            - name: REDIS_ADDRESS
              value: redis-service
            - name: PATH_CONF
              value: ../config
            - name: FILE_CONF
              value: local.conf

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - port: 8080
      targetPort: 8080